/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Timer1Delay.H
**     Project   : V9_1_2_51CN128
**     Processor : MCF51CN128CLK
**     Beantype  : TimerInt
**     Version   : Bean 02.157, Driver 01.17, CPU db: 3.00.014
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 6/10/2010, 5:19 PM
**     Abstract  :
**         This bean "TimerInt" implements a periodic interrupt.
**         When the bean and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : TPM1 (16-bit)
**         Compare name                : TPM10
**         Counter shared              : Yes
**
**         High speed mode
**             Prescaler               : divide-by-4
**             Clock                   : 6000000 Hz
**           Initial period/frequency
**             Xtal ticks              : 312
**             microseconds            : 10000
**             milliseconds            : 10
**             seconds (real)          : 0.01
**             Hz                      : 100
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Disabled
**              Events                 : Disabled
**
**         Timer registers
**              Counter                : TPM1CNT   [0xFFFF8261]
**              Mode                   : TPM1SC    [0xFFFF8260]
**              Run                    : TPM1SC    [0xFFFF8260]
**              Prescaler              : TPM1SC    [0xFFFF8260]
**
**         Compare registers
**              Compare                : TPM1C0V   [0xFFFF8266]
**
**         Flip-flop registers
**              Mode                   : TPM1C0SC  [0xFFFF8265]
**     Contents  :
**         Enable       - byte Timer1Delay_Enable(void);
**         Disable      - byte Timer1Delay_Disable(void);
**         EnableEvent  - byte Timer1Delay_EnableEvent(void);
**         DisableEvent - byte Timer1Delay_DisableEvent(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __Timer1Delay
#define __Timer1Delay

/* MODULE Timer1Delay. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"
extern bool Timer1Delay_EnEvent;       /* Enable/Disable events */


byte Timer1Delay_Enable(void);
/*
** ===================================================================
**     Method      :  Timer1Delay_Enable (bean TimerInt)
**
**     Description :
**         This method enables the bean - it starts the timer. Events
**         may be generated (<DisableEvent>/<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte Timer1Delay_Disable(void);
/*
** ===================================================================
**     Method      :  Timer1Delay_Disable (bean TimerInt)
**
**     Description :
**         This method disables the bean - it stops the timer. No
**         events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define Timer1Delay_EnableEvent() (Timer1Delay_EnEvent = TRUE, (byte)ERR_OK) /* Set the flag "events enabled" */
/*
** ===================================================================
**     Method      :  Timer1Delay_EnableEvent (bean TimerInt)
**
**     Description :
**         This method enables the events.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define Timer1Delay_DisableEvent() (Timer1Delay_EnEvent = FALSE, (byte)ERR_OK) /* Set the flag "events disabled" */
/*
** ===================================================================
**     Method      :  Timer1Delay_DisableEvent (bean TimerInt)
**
**     Description :
**         This method disables the events.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

__interrupt void Timer1Delay_Interrupt(void);
/*
** ===================================================================
**     Method      :  Timer1Delay_Interrupt (bean TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void Timer1Delay_Init(void);
/*
** ===================================================================
**     Method      :  Timer1Delay_Init (bean TimerInt)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


/* END Timer1Delay. */

#endif /* ifndef __Timer1Delay */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.06 [04.26]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
