/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : rtcINT.c
**     Project   : fileLib
**     Processor : MCF51CN128CLK
**     Component : ExtInt
**     Version   : Component 02.094, Driver 01.22, CPU db: 3.00.030
**     Compiler  : CodeWarrior ColdFireV1 C Compiler
**     Date/Time : 9/1/2010, 3:09 PM
**     Abstract  :
**         This component "ExtInt" implements an external 
**         interrupt, its control methods and interrupt/event 
**         handling procedure.
**         The bean uses one pin which generates interrupt on 
**         selected edge.
**     Settings  :
**         Interrupt name              : Virq
**         User handling procedure     : rtcINT_OnInterrupt
**
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       45            |  PTC4_IRQ_SS1_ADP11
**             ----------------------------------------------------
**
**         Port name                   : PTC
**
**         Bit number (in port)        : 4
**         Bit mask of the port        : 0x0010
**
**         Signal edge/level           : falling
**         Priority                    : 735
**         Pull option                 : off
**         Initial state               : Enabled
**
**         Edge register               : IRQSC     [0xFFFF80E0]
**         Enable register             : IRQSC     [0xFFFF80E0]
**         Request register            : IRQSC     [0xFFFF80E0]
**
**         Port data register          : PTCD      [0xFFFF8020]
**         Port control register       : PTCDD     [0xFFFF8021]
**     Contents  :
**         Enable  - void rtcINT_Enable(void);
**         Disable - void rtcINT_Disable(void);
**         GetVal  - bool rtcINT_GetVal(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#include "rtcINT.h"

/*Including shared modules, which are used for all project*/

#include "Events.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  rtcINT_Enable (component ExtInt)
**
**     Description :
**         Enable the component - the external events are accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void rtcINT_Enable(void)

**      This method is implemented as macro. See rtcINT.h file.      **
*/

/*
** ===================================================================
**     Method      :  rtcINT_Disable (component ExtInt)
**
**     Description :
**         Disable the component - the external events are not accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void rtcINT_Disable(void)

**      This method is implemented as macro. See rtcINT.h file.      **
*/

/*
** ===================================================================
**     Method      :  rtcINT_Interrupt (component ExtInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the components event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(rtcINT_Interrupt)
{
  /* IRQSC: IRQACK=1 */
  setReg8Bits(IRQSC, 0x04);            /* Clear the interrupt flag */ 
  rtcINT_OnInterrupt();                /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  rtcINT_GetVal (component ExtInt)
**
**     Description :
**         Returns the actual value of the input pin of the component.
**     Parameters  : None
**     Returns     :
**         ---             - Returned input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
** ===================================================================
*/
/*
bool rtcINT_GetVal(void)

**      This method is implemented as macro. See rtcINT.h file.      **
*/

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.09 [04.41]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
